version: '3.9'

services:
  app-blue:
    image: ${BLUE_IMAGE}
    environment:
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
    ports:
      - "8081:3000"

  app-green:
    image: ${GREEN_IMAGE}
    environment:
       - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
    ports:
      - "8082:3000"

  nginx:
    image: nginx:alpine
    ports:
      - "8060:8080"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template
      - nginx-logs:/var/log/nginx
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL:-blue}
    command: >
      sh -c "envsubst '$$ACTIVE_POOL' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      - app-blue
      - app-green
    labels:
      - "traefik.enable=false"

  alert-watcher:
    build: 
      context: .
      dockerfile: Dockerfile.watcher
    volumes:
      - nginx-logs:/var/log/nginx:ro
    environment:
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - ERROR_RATE_THRESHOLD=${ERROR_RATE_THRESHOLD:-2}
      - WINDOW_SIZE=${WINDOW_SIZE:-200}
      - ALERT_COOLDOWN_SEC=${ALERT_COOLDOWN_SEC:-300}
      - MAINTENANCE_MODE=${MAINTENANCE_MODE:-false}
    depends_on:
      - nginx
    restart: unless-stopped

volumes:
  nginx-logs:
